spring.application.name=logdetector
# datasource
spring.datasource.url=jdbc:h2:mem:logdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# h2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# optional (SQL formatting)
spring.jpa.properties.hibernate.format_sql=true

# 1. ???? SQL ?? ?? (DEBUG ??)
logging.level.org.hibernate.SQL=DEBUG

# 2. SQL? ????? ???? ? ?? (TRACE ??)
# Hibernate 6.x/7.x ??: descriptor.sql ?? ?? ??? ???? ???.
logging.level.org.hibernate.orm.jdbc.bind=TRACE
# redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#kafka
# Kafka \uBE0C\uB85C\uCEE4 \uC8FC\uC18C (\uB3C4\uCEE4 \uC678\uBD80\uC778 \uC708\uB3C4\uC6B0\uC5D0\uC11C \uC811\uC18D\uD558\uBBC0\uB85C 9092 \uC0AC\uC6A9)
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=log-group
spring.kafka.consumer.auto-offset-reset=earliest

# \uC9C1\uB82C\uD654 \uC124\uC815
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# \uC5ED\uC9C1\uB82C\uD654 \uC124\uC815
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*