spring.application.name=logdetector
# datasource
spring.datasource.url=jdbc:h2:mem:logdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# h2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# optional (SQL formatting)
spring.jpa.properties.hibernate.format_sql=true

# 1. ???? SQL ?? ?? (DEBUG ??)
logging.level.org.hibernate.SQL=DEBUG

# 2. SQL? ????? ???? ? ?? (TRACE ??)
# Hibernate 6.x/7.x ??: descriptor.sql ?? ?? ??? ???? ???.
logging.level.org.hibernate.orm.jdbc.bind=TRACE
# redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#kafka
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=log-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*